# Introducción a Numpy y Matplotlib

<img src="img/3-numpy/numpy_logo.jpg" width=200>

# Que es numpy?

En la sesión anterior vimos que una de las estrucutras de datos fundamentales en python son las listas. A pesar de ser un elemento muy útil en el mundo de la programación, esta estructura de datos es ineficiente cuando queremos considerar estas listas como vectores.

Por ejemplo,

```python

lista_1 = [1, 2, 3]
lista_2 = [2, 3, 4]

suma_lista_1_2 = lista_1 + lista_2

print(suma_lista)

# output
[1, 2, 3, 2, 3, 4]
```

Si quisieramos sumar elemento a elemento, deberíamos crearnos una función con bucles que nos devolviese el vector resultante.

In [7]:
## Escribe una función que dadas dos listas nos
## devuelva la suma elemento a elemento.
## Ojo! Acuerdate de comprobar que son del mismo tamaño!

##Extra: Echale un vistazo a la funcion zip() de python.
##Usando zip y las list comprehensions podemos reescribir
##la función en una linea de forma pythonica!

Como veis en el ejemplo anterior, no solo es innecesariamente complicado si no que es ineficiente cuando queremos tratar con vectores de gran tamaño. Sería conveniente tener operaciones definidas para este tipo de problemas.

Eso es exactamente lo que hace **Numpy**. Interpreta las listas como vectores numéricos y nos permite realizar operaciones de algebra lineal de forma eficiente.

Por si no fuera poco, **Numpy** está escrito en **C**, uno de los lenguajes de programación más [rápidos](https://attractivechaos.github.io/plb/). Además de proporcionarnos velocidad a la hora de realizar cálculos algebráicos, sirve cómo interfaz para comunicarse con funcionalidades escritas en **C** y en **Fortran**. Ésta es la razón principal por la **Numpy** nos importa cómo analistas o cientificos de datos, aunque no trabajemos directamente en algebra: los principales módulos para el análisis de datos (pandas y sklearn) se basan en **Numpy**, por lo que entender su estructura y uso nos facilitara la comprensión de las librerias de más alto nivel.



In [8]:
## importar numpy bajo el alias np

## `np.array` y `np.ndarray`

### `np.ndarray`

De la [documentación](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.html) oficial:

>  Describes an N-dimensional collection of “items” of the same type.

### `np.array`

Es un metodo de numpy que nos permite crear np.ndarray


### Crear un array a partir de listas

Para crear un array a partir de una lista, simplemente debemos pasar la lista como argumento a la función np.array()

```python

mi_lista = [1, 2, 3]

mi_array = np.array(mi_lista)

print(type(mi_array))
```

También, podemos crear un array a partir de una lista de listas.

```python

mi_lista_anidada = [[1, 2, 3],
                    [4, 5, 6]]

mi_array_2d = np.array(mi_lista_anidada)
```
                   

In [13]:
## Crea un ndarray a partir de una lista anidada


## Atributos de np.ndarray

Cada array tiene los atributos:

* `ndim`: el número de dimensionesthe number of dimensiones
* `shape`: el tamaño de cada dimensión
* `size`: el tamaño total del array

In [16]:
## Comprueba los atributos del array creado antes

## Arrays de números aleatorios

Numpy tiene una funcionalidad muy útil para generar datos de forma aleatoria o siguiendo alguna distribución estadística.

```python
gauss_dist = np.random.normal(loc=0,
                              scale=1,
                              size=(1000, 2))
```

In [41]:
## inicializar un vector aleatorio de enteros
np.random.seed(0)  # semilla for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array

In [59]:
## crea un array de 200 filas y 3 columnas aleatorio que siga una distribución
## de poisson

## Indexing
Sigue un patron similar a las listas de python.

Para acceder al $i^{th}$ elemento de una array 1-dimensional se sigue la sintaxis de braquets.

Para acceder al $i^{th}$ elemento de una array 2-dimensional se sigue la sintaxis de braquets con los indices separados por comas.

In [61]:
## accede al primer, tercer y quinto elemento de x1.

In [64]:
## accede al elemento de la primera fila y segunda columna de x2

## Slicing

De la misma forma que hacemos "slices" de listas en python podemos crearlos en los np.array.

Además, podemos especificar un "step", que es la cantidad de elementos que se saltara entre uno y otro.


x[start:stop:step]

Si no se especifica alguno de ellos, numpy toma el valor por defecto, que son:

* start=0
* stop=tamaño de la dimensión
* step=1

In [65]:
## Crea un array de una dimension con los numeros del 0 al 9 usando arange

In [66]:
## Crea un slice que contenga los 3 primeros elementos

In [67]:
## Crea un slice que contenga los 2 ultimos elementos

In [ ]:
## Crea un slice que contenga los elementos uno si y uno no

#### Ojo! si el paso es negativo los campos de start y stop se invierten. Es una forma muy conveniente de invertir el orden de un array

In [81]:
ordered = np.arange(10)
print(ordered)
reverse_order = ordered[::-1] 
print(reverse_order)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


## Multidimensiones

Hay que especificar el sub-slice en cada una de las dimensiones separados por coma en braquets


```python

x = np.array([[3, 5, 2, 4],
              [7, 6, 8, 8],
              [1, 6, 7, 7]])
# columnas
x[:, 2]
# output
array([2, 8, 7])

# filas
x[1, :]

# output
array([7, 6, 8, 8])
```

In [96]:
## accede a la primera columna

In [91]:
## accede a la segunda columna

In [94]:
## elimina la primera fila

## Expresiones matemáticas y funciones útiles

Numpy permite evaluar expresiones matematicas y funciones de forma sencilla y eficiente.

Por ejemplo:

```python

x = np.random.randint(10, size=20)

add_5_element_wise = x + 5
```

Suma `5` a cada elemento del array. Esto funciona de forma similar para las funciones aritméticas básicas (+, -, \*,...)

In [101]:
# crea un array aleatorio y multiplica cada uno de sus elementos por 3

### Funciones trigonométricas

In [118]:
# Crea un vector de 5 elementos espaciados de forma homogenea
# entre 0 y pi, ambos incluidos
x = np.linspace(0, np.pi, 5)

In [121]:
print(x)
sin_x = np.sin(x)


[ 0.          0.78539816  1.57079633  2.35619449  3.14159265]


In [113]:
# demuestra el teorema fundamental de la trigonometria

## Exponentes y logaritmos

In [122]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [  2.71828183   7.3890561   20.08553692]
2^x   = [ 2.  4.  8.]
3^x   = [ 3  9 27]


In [123]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [ 0.          0.69314718  1.38629436  2.30258509]
log2(x)  = [ 0.          1.          2.          3.32192809]
log10(x) = [ 0.          0.30103     0.60205999  1.        ]


Unas transformaciones muy útiles cuando lidiamos con valores pequeños son:

In [124]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [ 0.          0.0010005   0.01005017  0.10517092]
log(1 + x) = [ 0.          0.0009995   0.00995033  0.09531018]


### Ejercicios

Utiliza el cheatsheet disponible o busca las funcionalidades pertinentes

1. Crea una matriz identidad de $4 \times 4$
2. Genera el array siguiente sin crear la lista
```
1 2 3
4 5 6
7 8 9
```
3. Genera una matrix aleatoria de $4 \times 4 \times 4$ con números distribuidos siguiendo una gaussiana
4. Genear `n` intervalos entre 0 and 1 distribuidos de forma logarítmica